---
title: "Using CAX HLI data"
description: "About the CAX data, using it, and citing it"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Using CAX HLI data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Using CAX HLI data
IMPORTANT! BE SURE TO CAREFULLY READ AND UNDERSTAND THE TERMS AND CONDITIONS SET FORTH IN THIS END-USER LICENSE AGREEMENT. YOU WILL BE ASKED TO REVIEW AND EITHER ACCEPT OR NOT ACCEPT THE TERMS OF THE EULA. YOU ARE NOT AUTHORIZED TO ACCESS OR USE THE DATA IN THIS DATABASE UNLESS AND UNTIL YOU ACCEPT THE TERMS OF THIS EULA.

In order to access, share, or use these datasets you agree that:

1. You acknowledge that data in the StreamNet database are dynamic and may be updated at any time. Notification of data updates will be posted on the StreamNet website.

2. Data contributors, StreamNet, PSMFC, and Bonneville Power Administration accept no responsibility or liability for the accuracy of these data or for the uses and/or interpretations to which these data may be put.

3. Data contributors have uploaded links to the metadata and associated publications that may discuss the limitations and proper use of the data. It is your responsibility to understand and comply with these restrictions if you use the data.

4. We may take measures to restrict access to these data if violations occur, to ensure violations are not repeated.

5. You will be careful to properly credit individuals and agencies when using data, and will follow reputable standards for the use and interpretation of scientific information.

6. You assume responsibility to determine the usability of the data for your purposes.

7. Before publication, you will contact the appropriate data contributors and to maintain a record of contact prior to significant use of data in any publication in order to:

    a. obtain verification, data use limitations and context for data through metadata records.

    b. secure appropriate permissions prior to submission for publication by sending requests to data owners and cc’ing the data publishers or peer review team.

    c. arrange appropriate acknowledgements, citations and/or authorships.

8. Failure to comply with the requirements may result in denial of access to data files in future requests. (Data owners have 90 days to respond to data publication reviews). You will be notified of any accusations of failure to comply and have opportunities to defend your action to ensure continued access.

9. StreamNet will endeavor to design and maintain access to CA data for only those that agree to comply with this EULA. However, PSMFC – StreamNet does not accept any liability for this DSA, or for any compliance failure, or any responsibility for enforcement of this agreement or for the use or misuse of any data accessed through this database.

## About the data

These data are provided to the CAX by agencies and tribes in order to increase collaboration opportunities and consistency in analyses. StreamNet and CAP host and help develop the Data Exchange Standards, but responsibility and rights are retained by the data providers. Data accessibility or versioning access requests should be directed to `project@streamnet.org` and questions about the datasets or appropriate use should be directed towards the Contact Agency (`contactagency` column) or the Contact Person (`contactpersonfirst`, `contactpersonlast`, `contactphone` and `contactemail` columns). 
## How data quality is indicated

For the VR/SR datasets, CAX data is initially filtered for ESA listed population data by NMFS_POPID (`nmfs_popid`). POPID numbers are consecutive within an ESU. Note - this does not include superpops data, that has to be separately queried.


## Where and how to find the citation information

The metadata columns from the downloaded HLI data provide the necessary information to produce a citation. The columns that you need are described below.

**Recommended dataset citation format:**

Dataset Name (date range). Type of data. Data provider and contributor/s. Protocol and methods available at website. Data accessed by consumer name, version or date accessed from website. 

**Example:**

Salmon, Chinook (Snake River spring/summer-run ESU) East Fork South Fork Salmon River - summer (1987-2018). Natural Origin Spawner Abundance. Nez Perce Tribe and Idaho Department of Fish and Game. Protocols and methods available at https://www.monitoringresources.org/Document/Protocol/Details/2246. Accessed from www.cax.streamnet.org version May 26 2020 10:00PM by Mari Williams, NOAAF NWFSC/PSMFC.

### Metadata columns

* Dataset name:   `esapopname` column.
* Date range: For NOSA tables, the year is in the `spawningyear` column. min and max of this column gives the data range.
* Type of data: The HLI name is generally what the data type is. However, for NOSA (Natural origin spawner abundance) tables, you will need to look at the notes for each data row as data are escapement (natural and non-natural origin).
* Data provider: the `contactagency` and `otherdatasources` columns.
* Protocol and methods: `protmethurl` column.
* Data accessed by: Your name.
* Data version: `datasetversion` column name.
